server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy reverso simplificado para o Streamlit
    location /dashboard {
        # SRE: FQDN interno do Docker/K8s em vez de localhost
        proxy_pass http://analytics:8501; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Essencial para os WebSockets do Streamlit funcionarem
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Removemos o bloco /_stcore externo, pois ele agora é servido 
    # automaticamente dentro do bloco /dashboard
}
