from typing import Dict

MAPA_CORES_RISCO: Dict[str, str] = {
    "VERMELHO": "#ef4444",
    "LARANJA": "#f97316",
    "AMARELO": "#eab308",
    "VERDE": "#22c55e",
    "AZUL": "#3b82f6",
    "BRANCO": "#e5e7eb",
    "Não Informado": "#9ca3af",
}

MAPA_NOMENCLATURAS: Dict[str, str] = {
    "entidade_especialidade_especialidadeMae_descricao": "Parent Specialty",
    "entidade_especialidade_descricao": "Fine Specialty",
    "entidade_especialidade_cbo_descricao": "CBO Specialty",
    "entidade_cidPrincipal_codigo": "Main ICD (Code)",
    "entidade_cidPrincipal_descricao": "Main ICD (Description)",
    "origem_lista": "Source (List)",
    "situacao": "Current Situation",
    "entidade_especialidade_tipoRegulacao": "Regulation Type",
    "entidade_especialidade_ativa": "Active Specialty",
    "entidade_especialidade_teleconsulta": "Accepts Teleconsultation",
    "entidade_centralRegulacao_nome": "Regulation Center",
    "entidade_unidadeOperador_centralRegulacao_nome": "Operating Unit Reg. Center",
    "liminarOrdemJudicial": "Injunction / Court Order",
    "entidade_unidadeOperador_nome": "Operating Unit",
    "entidade_unidadeOperador_razaoSocial": "Operating Unit (Corporate Name)",
    "entidade_unidadeOperador_tipoUnidade_descricao": "Operating Unit Type",
    "medicoSolicitante": "Requesting Doctor",
    "operador_nome": "Operator",
    "usuarioSolicitante_nome": "Requesting User",
    "evolucoes_json": "Information Source",
    "historico_evolucoes_completo": "Information Type",
    "entidade_complexidade": "Complexity",
    "entidade_classificacaoRisco_cor": "Risk Classification Color",
    "corRegulador": "Regulator Color",
    "usuarioSUS_municipioResidencia_nome": "Municipality of Residence",
    "usuarioSUS_bairro": "Neighborhood",
    "usuarioSUS_sexo": "Sex",
    "usuarioSUS_racaCor": "Race/Color",
    "usuarioSUS_nacionalidade": "Nationality",
}
